### ISSUE TITLE
Unable to view the app on Bluemix dashboard

### ISSUE THREAD

**Issue by jinglerobs** [IBMDevConnect17/TelcoChatBot#1]
I have clicked the "Deploy to Bluemix" button and I m redirected to Bluemix where is select the 'Organization' and space to deploy the code. Post deployment I can see only service list on Bluemix dashboard as below:
1. cloudant-db
2. conversation service

I m not able to see the 'telco chat bot' app under Apps section. I have trie this deployment multiple times with different Bluemix IDs but same issue is there.
Please advise.

Thanks
Robin Thomas

**Comment by jinglerobs** [comment]
After using the new commit code, I m getting slightly different error message while deploying to Bluemix dashboard
FAILED
Could not find plan with name Lite
[cf-logs2.txt](https://github.com/IBMDevConnect17/TelcoChatBot/files/1217115/cf-logs2.txt)

**Comment by sudharshan-govindan** [comment]
Hi Robin,

In the manifest.yml, the value for plan variable of Discovery has changed. We have updated it with correct value and we are able to deploy with out any isssues.

Can you please try again ?

Thanks,
Sudharshan Govindan

**Comment by jinglerobs** [comment]
Thanks Sudarshan, updated code is working fine. I m able to see the app in Bluemix Dashboard.
Regards
Robin Thomas
